select A.ANIMAL_ID,A.ANIMAL_TYPE, A.NAME
from ANIMAL_INS A
join ANIMAL_OUTS B
on A.ANIMAL_ID=B.ANIMAL_ID
where A.SEX_UPON_INTAKE like 'INTACT%'
and (B.SEX_UPON_OUTCOME like 'SPAYED%'
or B.SEX_UPON_OUTCOME like 'NEUTERED%')
order by A.ANIMAL_ID