SELECT
ITEM_ID,
ITEM_NAME,
RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_TREE.ITEM_ID 
    FROM ITEM_TREE
    JOIN ITEM_INFO ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
    WHERE ITEM_INFO.RARITY = 'RARE') 
         
ORDER BY ITEM_ID DESC