SELECT
E.DEPT_ID AS DEPT_ID,
D.DEPT_NAME_EN AS DEPT_NAME_EN,
ROUND(AVG(E.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES AS E
JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
GROUP BY E.DEPT_ID
ORDER BY AVG_SAL DESC
